build:
    environment:
        php: 7.4.11
    nodes:
        coverage:
            tests:
                override:
                    -   command: composer unit-coverage
                        coverage:
                            file: phpunit.xml
                            format: clover
filter:
    excluded_paths: [ vendor/*, Tests/* ]
checks:
    php:
        code_rating: true
        duplication: true