build:
    environment:
        php: 7.4.11
filter:
    excluded_paths: [vendor/*, Tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true